copy project files
jacob-js/google-search-ui pull request #1
Opened 2022-10-17 15:04 UTC by jacob-js

2022-10-18 10:36 UTC, mutesialine reviewed
well done @jacob-js  i left some comment below try to make some changes on few things

2022-10-18 10:36 UTC, mutesialine commented on index.html
> +                <div class="footer--link">Settings</div>
according to the instructions use tailwindcss in your index.html remove those classes

2022-10-18 10:36 UTC, mutesialine commented on style.css
> +    }
these classes in style .css  are not allowed style it in index.html

2022-10-18 10:36 UTC, mutesialine commented on index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
no framework is allowed to use  try to inspect on  google site  and find icon they used or visit heroicon it has icon made by tailwindcss

2022-10-18 10:36 UTC, mutesialine commented on index.html
> +            <a href="#" class="lang-link">Kinyarwanda</a>
also here remove classes   use tailwindcss in html

2022-10-18 10:51 UTC, serapieTuyishime requested changes
remove the BEM and abstract classes

2022-10-18 10:51 UTC, serapieTuyishime commented on index.html
> +        <div class="border border-gray-300 rounded-3xl relative flex items-center px-4 mt-10 w-[90%] lg:w-2/5 hover:shadow-md">
this 90% should be defined in tailwind.config.js

2022-10-18 10:51 UTC, serapieTuyishime commented on index.html
> +            <input type="text" class="outline-none bg-none border-none py-[10px] ml-3 w-full">
no abstract classes

2022-10-18 10:51 UTC, serapieTuyishime commented on index.html
> +            <button class="action-btn">Google Search</button>
no BEN should be used, all the tailwindcss classes should be put here.

2022-10-18 10:51 UTC, serapieTuyishime commented on index.html
> +            <a href="#" class="lang-link">Français</a>
no BEM should be used.

2022-10-18 10:51 UTC, serapieTuyishime commented on index.html
> +        <div class="footer--links flex justify-center flex-wrap gap-5 sm:justify-between px-10 py-3">
footer--links should be replaced by its corresponding classes

2022-10-18 10:51 UTC, serapieTuyishime commented on index.html
> +                <div class="footer--link">Settings</div>
even though it is repetition, replace all classes in footer--link with their classes

2022-10-18 18:13 UTC, serapieTuyishime requested changes

2022-10-18 18:13 UTC, serapieTuyishime commented on index.html
> +            <input type="text" class="outline-none bg-none border-none py-[10px] ml-3 w-full">
py-[10px] is an abstract class and it is not allowed you should do this in config file

2022-10-19 07:23 UTC, serapieTuyishime approved these changes
Thanks for making the changes

2022-10-19 10:07 UTC, mutesialine approved these changes

2022-10-25 13:06 UTC, karemarsy approved these changes

2022-10-26 08:33 UTC, merged